### ISSUE TITLE
Add MailHog Docker Container

### ISSUE THREAD

**Issue by kdcllc** [JudahGabriel/Chavah#66]
Add MailHog Docker Container for emails testing while in development.
https://github.com/ian-kent/MailHog
https://hub.docker.com/r/mailhog/mailhog/

Docker-compose entry
```
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
```
